# Generated by Django 4.2.13 on 2024-07-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors', models.ManyToManyField(to='doctorapp.schedule')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.registeration')),
            ],
        ),
        migrations.CreateModel(
            name='bookingitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.booking')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.schedule')),
            ],
        ),
    ]
