# Generated by Django 4.2.13 on 2024-07-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
