# Generated by Django 4.2.13 on 2024-07-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=200)),
                ('workingtime', models.CharField(max_length=200)),
                ('numoftickets', models.PositiveIntegerField()),
                ('docdepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.department')),
            ],
        ),
    ]
