# Generated by Django 4.2.13 on 2024-07-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='docimage',
            field=models.ImageField(default=2345, upload_to=''),
            preserve_default=False,
        ),
    ]
