# Generated by Django 4.2.13 on 2024-07-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_schedule_docimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
