# Generated by Django 4.2.13 on 2024-07-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_registeration_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presc_det', models.CharField(max_length=200)),
                ('presc_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.medicine')),
                ('presc_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.registeration')),
            ],
        ),
    ]
