# Generated by Django 4.2.13 on 2024-07-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0005_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='presc_num',
            field=models.IntegerField(default=1),
        ),
    ]
