# Generated by Django 4.2.13 on 2024-07-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0006_prescription_presc_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='labtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userdiaganosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaganosis_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.registeration')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.labtest')),
            ],
        ),
    ]
