# Generated by Django 4.2.13 on 2024-07-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0007_labtest_userdiaganosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiaganosis',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
